# ===================================
#  List Behavior Config
# ===================================

title: Manage Certifications
list: @/plugins/cnesmeteo/user/models/certification/columns.yaml
modelClass: CnesMeteo\User\Models\Certification
recordUrl: cnesmeteo/user/certifications/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
