# ===================================
#  List Behavior Config
# ===================================

title: Manage Sites
list: @/plugins/cnesmeteo/user/models/site/columns.yaml
modelClass: CnesMeteo\User\Models\Site
recordUrl: cnesmeteo/user/sites/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showCheckboxes: true

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt



