# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/cnesmeteo/localization/models/province/columns.yaml

# Model Class name
modelClass: CnesMeteo\Localization\Models\Province

# List Title
title: Manage Provinces

# Link URL for each record
recordUrl: cnesmeteo/localization/province/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Default sorting column
defaultSort:
    column: name
    direction: asc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
